spring:
  application:
    name: demo-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/weir_permissions?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 336393
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  boot: 
    admin: 
      client: 
        url: http://localhost:54321
# ===================================================================
# 服务发现
# ===================================================================    
eureka: 
  instance: 
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 15  #超时时间,默认为90秒,该值至少应该大于leaseRenewalIntervalInSeconds
    lease-renewal-interval-in-seconds: 5      #eureka client发送心跳给server端的频率,默认30秒
  client: 
    register-with-eureka: true
    registryFetchIntervalSeconds: 5       #取服务注册信息间隔，默认为30秒
    #指定服务注册中心的地址,高可用集群时指向其他的eureka服务相互注册，多个用","分割
    serviceUrl: 
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/

management.security.enabled: false

server:
  port: 6801
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.kj.ordercenter.demo.provider
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    db-config:
      id-type: ID_WORKER
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
    #驼峰下划线转换
      table-underline: true
    #刷新mapper 调试神器
    ##refresh: false
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
