server:
  port: 6900

# ===================================================================
# 服务发现
# ===================================================================    
eureka: 
  instance: 
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 15  #超时时间,默认为90秒,该值至少应该大于leaseRenewalIntervalInSeconds
    lease-renewal-interval-in-seconds: 5      #eureka client发送心跳给server端的频率,默认30秒
  client: 
    register-with-eureka: true
    registryFetchIntervalSeconds: 5       #取服务注册信息间隔，默认为30秒
    #指定服务注册中心的地址,高可用集群时指向其他的eureka服务相互注册，多个用","分割
    serviceUrl: 
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/
spring:
  application:
    name: demo-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # JDBC连接Mysql6以上com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.233:3306/ordercenter?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: sql@kdn!123
    hikari:
      minimum-idle: 5 ## 最小空闲连接数量
      idle-timeout: 180000 ## 空闲连接存活最大时间，默认600000（10分钟
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
      auto-commit: true ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      maxLifetime: 600000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
    
# ===================================================================
# mybatis配置
# ===================================================================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kj.demo.service