spring:
  application:
    name: register-center

eureka: 
  instance:
    hostname: eureka1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #超时时间,默认为90秒,该值至少应该大于leaseRenewalIntervalInSeconds
    lease-expiration-duration-in-seconds: 30 
    #eureka client发送心跳给server端的频率,默认30秒
    lease-renewal-interval-in-seconds: 10
  server:       #EurekaServerConfigBean
    #自我保护
    enable-self-preservation: true
    # 清理间隔(单位毫秒，默认是60*1000)
    eviction-interval-timer-in-ms: 1000
  client: 
    #该应用为注册中心，设置为false, 表示不向注册中心注册自己, 高可用时需要设置为true
    register-with-eureka: false
    fetch-registry: false
    #取服务注册信息间隔，默认为30秒
    registryFetchIntervalSeconds: 5
    #指定服务注册中心的地址,高可用集群时指向其他的eureka服务相互注册，多个用","分割
    serviceUrl: 
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/

server:
  port: 8761

# ===================================================================
# 日志配置
# ===================================================================      
logging: 
  config: classpath:cust-logback.xml
  path: /opt/logs